### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by francesco-gaglione** [francesco-gaglione/AppHub#1]
# Settings
Develop app settings to allow user to set their preferencies.

Settings should have two category: general and advanced.

## ToDos

- [x] create settings model
- [x] create settings storage using tauri storage
- [x] create settings commands
- [x] create settings page
- [x] settings page comunications with commands
- [ ] general improvements
